# Generated by Django 5.0.1 on 2024-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_pagina', '0002_alter_exames_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='exames',
            name='concluido',
            field=models.BooleanField(default=True),
        ),
    ]
